[package]
name = "duplicate-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
dirs = "6.0.0"
image_hasher = "3.0.0"
serde_json = "1.0.140"
walkdir = "2.5.0"
